"""Contratos tipados compartidos de Nexo IA.

Este paquete es la fuente de verdad de los contratos de la sección 5 del plan de
Fase 0. Los JSON Schema publicados en `contracts/jsonschema/`, `contracts/events/`
y `contracts/examples/` se **generan** desde aquí con
`python -m nexo_contracts.export`; no se editan a mano.

Reglas de compatibilidad (`DIE-F0-007`): dentro de `v1` solo se admiten cambios
aditivos (campos opcionales nuevos, miembros nuevos de enum). Eliminar o
renombrar un campo, estrechar un tipo o volver obligatorio un campo opcional
exige publicar `v2`.
"""

from .a2ui import (
    A2UI_PROTOCOL_VERSION,
    A2UIAction,
    A2UIComponent,
    A2UIMessage,
    A2UISurface,
    A2UIValidationError,
    A2UIValidationResult,
    CatalogDescriptor,
    ChannelFallback,
    ComponentDescriptor,
    CreateSurface,
    UpdateComponents,
    UpdateDataModel,
)
from .base import CONTRACTS_SCHEMA_VERSION, FrozenNexoModel, NexoModel
from .enums import (
    CRITICAL_FACT_CATEGORIES,
    RETRYABLE_ERROR_CODES,
    TERMINAL_RUN_STATUSES,
    A2UIMessageKind,
    A2UIValidationOutcome,
    ActionStatus,
    ActorType,
    AgentName,
    Audience,
    Channel,
    ContradictionSeverity,
    ContradictionStatus,
    CorpusStatus,
    Domain,
    ErrorCode,
    EventStatus,
    EventType,
    FactCategory,
    FactOrigin,
    IngestionOutcome,
    IntegrationState,
    ModelDecisionReason,
    ModelHealth,
    ModelTaskKind,
    Outcome,
    RetrievalMode,
    RiskLevel,
    RunStatus,
    SourceStatus,
    TaskStatus,
    ToolCallStatus,
    ToolMode,
    VerificationStatus,
)
from .errors import (
    HTTP_STATUS_BY_ERROR_CODE,
    ConfigurationError,
    ErrorDetail,
    NormalizedError,
)
from .estimation import Estimate, EstimateStep
from .evaluation import (
    DeterministicEvaluationResult,
    EvaluationReport,
    JudgeRequest,
    JudgeResult,
    JudgeScores,
    SelfCheckResult,
)
from .events import EventActor, EventSequence, RunEvent
from .execution import (
    ActionRequest,
    ActionResult,
    AgentResult,
    AgentTask,
    Budgets,
    DeducedContextItem,
    Identity,
    Profile,
    ProposedToolCall,
    RunMetrics,
    RunRequest,
    RunResult,
    RunSnapshot,
    RunState,
)
from .facts import (
    CandidateFact,
    Contradiction,
    Deduction,
    FactValue,
    SourceCitation,
    VerifiedFact,
    VerifiedFacts,
)
from .model_gateway import (
    ModelAlias,
    ModelCandidate,
    ModelCapabilities,
    ModelDecision,
    ModelInvocation,
    ModelPolicy,
    ModelTask,
)
from .primitives import (
    CalendarDate,
    Confidence,
    CurrencyCode,
    Money,
    PositiveMillis,
    Score,
    SemanticVersion,
    Slug,
    UtcDatetime,
    ValidityWindow,
)
from .rag import (
    Chunk,
    CorpusVersion,
    Document,
    DocumentVersion,
    IngestionResult,
    RetrievalFilters,
    RetrievalQuery,
    RetrievalResponse,
    RetrievalResult,
    Source,
)
from .safety import SafePayload, reject_unsafe_keys
from .skills import SkillBudgets, SkillManifest, SkillStep
from .tools import (
    Approval,
    ControlledTestResult,
    IntegrationDraft,
    MapperValidation,
    PublishedToolVersion,
    ToolCall,
    ToolConfirmation,
    ToolError,
    ToolMetadata,
    ToolName,
    ToolPermissionContext,
    ToolResult,
)

__all__ = [
    "A2UI_PROTOCOL_VERSION",
    "CONTRACTS_SCHEMA_VERSION",
    "CRITICAL_FACT_CATEGORIES",
    "HTTP_STATUS_BY_ERROR_CODE",
    "RETRYABLE_ERROR_CODES",
    "TERMINAL_RUN_STATUSES",
    "A2UIAction",
    "A2UIComponent",
    "A2UIMessage",
    "A2UIMessageKind",
    "A2UISurface",
    "A2UIValidationError",
    "A2UIValidationOutcome",
    "A2UIValidationResult",
    "ActionRequest",
    "ActionResult",
    "ActionStatus",
    "ActorType",
    "AgentName",
    "AgentResult",
    "AgentTask",
    "Approval",
    "Audience",
    "Budgets",
    "CalendarDate",
    "CandidateFact",
    "CatalogDescriptor",
    "Channel",
    "ChannelFallback",
    "Chunk",
    "ComponentDescriptor",
    "Confidence",
    "ConfigurationError",
    "Contradiction",
    "ContradictionSeverity",
    "ContradictionStatus",
    "ControlledTestResult",
    "CorpusStatus",
    "CorpusVersion",
    "CreateSurface",
    "CurrencyCode",
    "DeducedContextItem",
    "Deduction",
    "DeterministicEvaluationResult",
    "Document",
    "DocumentVersion",
    "Domain",
    "ErrorCode",
    "ErrorDetail",
    "Estimate",
    "EstimateStep",
    "EvaluationReport",
    "EventActor",
    "EventSequence",
    "EventStatus",
    "EventType",
    "FactCategory",
    "FactOrigin",
    "FactValue",
    "FrozenNexoModel",
    "Identity",
    "IngestionOutcome",
    "IngestionResult",
    "IntegrationDraft",
    "IntegrationState",
    "JudgeRequest",
    "JudgeResult",
    "JudgeScores",
    "MapperValidation",
    "ModelAlias",
    "ModelCandidate",
    "ModelCapabilities",
    "ModelDecision",
    "ModelDecisionReason",
    "ModelHealth",
    "ModelInvocation",
    "ModelPolicy",
    "ModelTask",
    "ModelTaskKind",
    "Money",
    "NexoModel",
    "NormalizedError",
    "Outcome",
    "PositiveMillis",
    "Profile",
    "ProposedToolCall",
    "PublishedToolVersion",
    "RetrievalFilters",
    "RetrievalMode",
    "RetrievalQuery",
    "RetrievalResponse",
    "RetrievalResult",
    "RiskLevel",
    "RunEvent",
    "RunMetrics",
    "RunRequest",
    "RunResult",
    "RunSnapshot",
    "RunState",
    "RunStatus",
    "SafePayload",
    "Score",
    "SelfCheckResult",
    "SemanticVersion",
    "SkillBudgets",
    "SkillManifest",
    "SkillStep",
    "Slug",
    "Source",
    "SourceCitation",
    "SourceStatus",
    "TaskStatus",
    "ToolCall",
    "ToolCallStatus",
    "ToolConfirmation",
    "ToolError",
    "ToolMetadata",
    "ToolMode",
    "ToolName",
    "ToolPermissionContext",
    "ToolResult",
    "UpdateComponents",
    "UpdateDataModel",
    "UtcDatetime",
    "ValidityWindow",
    "VerificationStatus",
    "VerifiedFact",
    "VerifiedFacts",
    "reject_unsafe_keys",
]
