export const solicitudes = [
  {
    folio: "NX-2026-004821",
    titulo: "Traspaso de vehículo",
    dominio: "Vehículos",
    estado: "En revisión",
    tone: "warning" as const,
    canal: "WhatsApp",
    actualizado: "Hoy, 09:42",
  },
  {
    folio: "NX-2026-004770",
    titulo: "Constitución de empresa (SRL)",
    dominio: "Empresas",
    estado: "Documentos pendientes",
    tone: "info" as const,
    canal: "Portal web",
    actualizado: "Ayer, 17:10",
  },
  {
    folio: "NX-2026-004612",
    titulo: "Certificado de nacimiento",
    dominio: "Registro civil",
    estado: "Completado",
    tone: "success" as const,
    canal: "Llamada de voz",
    actualizado: "28 jul, 11:05",
  },
];

export const runs = [
  {
    id: "run_9f2a41",
    fecha: "30 jul 2026 · 09:41",
    dominio: "Vehículos",
    canal: "WhatsApp",
    estado: "Completado",
    tone: "success" as const,
    duracion: "42 s",
    trace: "trc_8ac31e94b2",
    pasos: 7,
  },
  {
    id: "run_9f2a12",
    fecha: "30 jul 2026 · 09:12",
    dominio: "Empresas",
    canal: "Portal web",
    estado: "En curso",
    tone: "info" as const,
    duracion: "1 m 08 s",
    trace: "trc_5db09f7712",
    pasos: 4,
  },
  {
    id: "run_9f19cd",
    fecha: "30 jul 2026 · 08:55",
    dominio: "Salud",
    canal: "Voz",
    estado: "Error de herramienta",
    tone: "destructive" as const,
    duracion: "19 s",
    trace: "trc_71fe20aa03",
    pasos: 3,
  },
  {
    id: "run_9f18b0",
    fecha: "30 jul 2026 · 08:31",
    dominio: "Ganadería",
    canal: "WhatsApp",
    estado: "Completado",
    tone: "success" as const,
    duracion: "1 m 51 s",
    trace: "trc_44c8d1b6ff",
    pasos: 9,
  },
  {
    id: "run_9f1702",
    fecha: "30 jul 2026 · 07:58",
    dominio: "Registro civil",
    canal: "Portal web",
    estado: "Derivado a humano",
    tone: "warning" as const,
    duracion: "3 m 04 s",
    trace: "trc_92bb47e10c",
    pasos: 6,
  },
];

export const tendencia = [
  { dia: "24 jul", tramites: 268, exito: 91 },
  { dia: "25 jul", tramites: 302, exito: 93 },
  { dia: "26 jul", tramites: 214, exito: 90 },
  { dia: "27 jul", tramites: 341, exito: 94 },
  { dia: "28 jul", tramites: 388, exito: 92 },
  { dia: "29 jul", tramites: 402, exito: 95 },
  { dia: "30 jul", tramites: 361, exito: 96 },
];
